### ISSUE TITLE
安卓下面老是报错. 你另外一个项目好像是正常的  

### ISSUE THREAD

**Issue by laowus** [Predidit/BiliNeo#1]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':background_downloader:compileDebugKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':background_downloader:compileDebugKotlin'
   > Could not resolve all files for configuration ':background_downloader:kotlinCompilerPluginClasspathDebug'.
      > Could not find org.jetbrains.kotlin:kotlin-serialization-compiler-plugin-embeddable:1.7.10.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
          - https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
          - https://storage.flutter-io.cn/download.flutter.io/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
          - https://storage.googleapis.com/download.flutter.io/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
        Required by:
            project :background_downloader

**Comment by Predidit** [comment]
看上去是网络问题。

实在不行的话可以先移除这个依赖。

这个依赖是为番剧下载功能准备的，现在还没使用。
